name: torchsegmentation2
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python==3.10
  - pytorch::pytorch-cuda
  - pytorch::pytorch==2.0
  - pytorch::torchvision
  - nvidia::cudatoolkit
  - conda-forge::wandb
  - conda-forge::scikit-learn
  - conda-forge::scikit-image
  - conda-forge::nibabel
  - conda-forge::nilearn
  - conda-forge::opacus
  - ipykernel
  - matplotlib
  - conda-forge::h5py
  - conda-forge::pandas
  - black
  - pytest
  - pylint
  - pip
  - pip:
    - omegaconf
    - hydra-core==1.2.0
    - tqdm 
    - perflint
    - pytest-profiling
    - split-folders
    - pyyaml
    - deepee
    - objax
    - segmentation-models-pytorch
    - wandb
    - torchmetrics
    - monai
    - jax
    - jaxlib
    - torchinfo
    - opacus
    - git+https://github.com/a1302z/ACSConv
    - inplace-abn==1.1.0
    - onnx
    - onnxscript

